export const ActionTypes = {
  FOLDERS_BE_REQUEST: 'FOLDERS_BE_REQUEST',
  FOLDERS_SET: 'FOLDERS_SET',
  FOLDERS_ADD: 'FOLDERS_ADD',
  MESSAGES_BE_REQUEST: 'MESSAGES_BE_REQUEST',
  MESSAGES_SET: 'MESSAGES_SET',
  ADD_MESSAGE: 'ADD_MESSAGE'
};
