export const ActionTypes = {
  FOLDERS_BE_REQUEST: 'FOLDERS_BE_REQUEST',
  FOLDERS_SET: 'FOLDERS_SET',
  FOLDERS_ADD: 'FOLDERS_ADD',
  MESSAGES_BE_REQUEST: 'MESSAGES_BE_REQUEST',
  MESSAGES_BE_REQUEST_COMPLETED: 'MESSAGES_BE_REQUEST_COMPLETED',
  MESSAGES_LOAD_FROM_CACHE: 'MESSAGES_LOAD_FROM_CACHE',
  MESSAGES_UPDATE_CACHE: 'MESSAGES_UPDATE_CACHE',
  MESSAGES_SET: 'MESSAGES_SET',
  ADD_MESSAGE: 'ADD_MESSAGE'
};
