export const ActionTypes = {
  APPLICATION_BE_REQUEST: 'APPLICATION_BE_REQUEST',
  APPLICATION_BE_REQUEST_COMPLETED: 'APPLICATION_BE_REQUEST_COMPLETED',
  APPLICATION_USER_CREDENTIALS_SET: 'APPLICATION_USER_CREDENTIALS_SET',
  APPLICATION_FOLDER_SELECT: 'APPLICATION_FOLDER_SELECT',
  APPLICATION_MESSAGE_SELECT: 'APPLICATION_MESSAGE_SELECT',
  APPLICATION_ERROR_SET: 'APPLICATION_ERROR_SET',
  FOLDERS_BE_REQUEST: 'FOLDERS_BE_REQUEST',
  FOLDERS_SET: 'FOLDERS_SET',
  FOLDERS_ADD: 'FOLDERS_ADD',
  MESSAGES_BE_REQUEST: 'MESSAGES_BE_REQUEST',
  MESSAGES_BE_REQUEST_COMPLETED: 'MESSAGES_BE_REQUEST_COMPLETED',
  MESSAGES_SET_CACHE: 'MESSAGES_SET_CACHE',
  MESSAGES_SET_FOLDER_CACHE: 'MESSAGES_SET_FOLDER_CACHE',
  MESSAGES_UPDATE_CACHE: 'MESSAGES_UPDATE_CACHE',
  ADD_MESSAGE: 'ADD_MESSAGE'
};
